// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "The Ink",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "The Ink",
            targets: ["AppModule"],
            bundleIdentifier: "byo.wwdc23-ssc",
            teamIdentifier: "3BWEDXDT2H",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft
            ],
            appCategory: .simulationGames
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resource")
            ]
        )
    ]
)